### ISSUE TITLE
INFOGRAFIA

### ISSUE THREAD

**Issue by Anamichel-leon** [SistemasTecTlaxiaco/actividad-1-infografia-Anamichel-leon#2]
[INFOGRAFIA.pdf](https://github.com/SistemasTecTlaxiaco/actividad-1-infografia-Anamichel-leon/files/12491512/INFOGRAFIA.pdf)

**Comment by JeroRoque** [comment]
calificación: 20/20

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
